# Generated by Django 2.2.1 on 2019-09-27 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='instructor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='courseInfo.Instructor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='courseInfo.Course'),
        ),
    ]
