# Generated by Django 2.2.1 on 2019-11-02 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseInfo', '0008_semester_schema_and_data_conversion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['year__year', 'period__period_sequence']},
        ),
        migrations.AlterField(
            model_name='semester',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semesters', to='courseInfo.Period'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semesters', to='courseInfo.Year'),
        ),
    ]
