# Generated by Django 2.2.1 on 2019-11-02 15:39

from __future__ import unicode_literals

from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations


INSTRUCTORS = [
    {
        'first_name': 'Leonard',
        'last_name': 'Buckland',
    },
    {
        'first_name': 'Megan',
        'last_name': 'Vance',
    },
    {
        'first_name': 'Blake',
        'last_name': 'Ferguson',
    },
    {
        'first_name': 'Stephanie',
        'last_name': 'Carr',
    },
    {
        'first_name': 'Jack',
        'last_name': 'Hill',
    },
    {
        'first_name': 'Zoe',
        'last_name': 'Sanderson',
    },
    {
        'first_name': 'Jasmine',
        'last_name': 'Gray',
    },
    {
        'first_name': 'Amy',
        'last_name': 'Scott',
    },
    {
        'first_name': 'Bella',
        'last_name': 'Bailey',
    },
    {
        'first_name': 'Jennifer',
        'last_name': 'Knox',
    },
    {
        'first_name': 'Anthony',
        'last_name': 'Underwood',
    },
    {
        'first_name': 'Isaac',
        'last_name': 'Reid',
    },
    {
        'first_name': 'Michelle',
        'last_name': 'Blake',
    },
    {
        'first_name': 'Lily',
        'last_name': 'Lewis',
    },
    {
        'first_name': 'Lauren',
        'last_name': 'Walker',
    },
    {
        'first_name': 'Gabrielle',
        'last_name': 'Lyman',
    },
    {
        'first_name': 'Anthony',
        'last_name': 'Peake',
    },
    {
        'first_name': 'Carol',
        'last_name': 'Scott',
    },
    {
        'first_name': 'Nicholas',
        'last_name': 'Skinner',
    },
    {
        'first_name': 'Ella',
        'last_name': 'Manning',
    },
    {
        'first_name': 'Dominic',
        'last_name': 'Sanderson',
    },
    {
        'first_name': 'Colin',
        'last_name': 'Dowd',
    },
    {
        'first_name': 'Theresa',
        'last_name': 'Edmunds',
    },
    {
        'first_name': 'Michelle',
        'last_name': 'Parsons',
    },
    {
        'first_name': 'Christopher',
        'last_name': 'Greene',
    },
    {
        'first_name': 'Mary',
        'last_name': 'Clark',
    },
    {
        'first_name': 'Kimberly',
        'last_name': 'Berry',
    },
    {
        'first_name': 'Yvonne',
        'last_name': 'Cameron',
    },
    {
        'first_name': 'Christian',
        'last_name': 'Skinner',
    },
    {
        'first_name': 'Lillian',
        'last_name': 'Poole',
    },
    {
        'first_name': 'Caroline',
        'last_name': 'Alsop',
    },
    {
        'first_name': 'Nicholas',
        'last_name': 'Underwood',
    },
    {
        'first_name': 'Rachel',
        'last_name': 'Mackay',
    },
    {
        'first_name': 'Sebastian',
        'last_name': 'Gibson',
    },
    {
        'first_name': 'Carol',
        'last_name': 'Paige',
    },
    {
        'first_name': 'Simon',
        'last_name': 'Buckland',
    },
    {
        'first_name': 'Faith',
        'last_name': 'Tucker',
    },
    {
        'first_name': 'Anna',
        'last_name': 'Vaughan',
    },
    {
        'first_name': 'Robert',
        'last_name': 'Lewis',
    },
    {
        'first_name': 'Abigail',
        'last_name': 'Paterson',
    },
    {
        'first_name': 'Victor',
        'last_name': 'Poole',
    },
    {
        'first_name': 'Julian',
        'last_name': 'Turner',
    },
    {
        'first_name': 'Leah',
        'last_name': 'Marshall',
    },
    {
        'first_name': 'Boris',
        'last_name': 'Knox',
    },
    {
        'first_name': 'Lillian',
        'last_name': 'Bell',
    },
    {
        'first_name': 'Austin',
        'last_name': 'McLean',
    },
    {
        'first_name': 'Stewart',
        'last_name': 'Tucker',
    },
    {
        'first_name': 'Una',
        'last_name': 'Nolan',
    },
    {
        'first_name': 'Claire',
        'last_name': 'Wright',
    },
    {
        'first_name': 'Madeleine',
        'last_name': 'Metcalfe',
    },
    {
        'first_name': 'Carol',
        'last_name': 'Hodges',
    },
    {
        'first_name': 'Bella',
        'last_name': 'Sharp',
    },
    {
        'first_name': 'Mary',
        'last_name': 'Glover',
    },
    {
        'first_name': 'Joshua',
        'last_name': 'Langdon',
    },
    {
        'first_name': 'Sophie',
        'last_name': 'Hamilton',
    },
    {
        'first_name': 'Felicity',
        'last_name': 'Welch',
    },
    {
        'first_name': 'Ella',
        'last_name': 'May',
    },
    {
        'first_name': 'Katherine',
        'last_name': 'Greene',
    },
    {
        'first_name': 'Blake',
        'last_name': 'Wallace',
    },
    {
        'first_name': 'Nicholas',
        'last_name': 'Sanderson',
    },
    {
        'first_name': 'Elizabeth',
        'last_name': 'Langdon',
    },
    {
        'first_name': 'Megan',
        'last_name': 'Pullman',
    },
    {
        'first_name': 'Joe',
        'last_name': 'Morrison',
    },
    {
        'first_name': 'Ella',
        'last_name': 'Lyman',
    },
    {
        'first_name': 'Sophie',
        'last_name': 'Hemmings',
    },
    {
        'first_name': 'Maria',
        'last_name': 'Carr',
    },
    {
        'first_name': 'Sean',
        'last_name': 'Morgan',
    },
    {
        'first_name': 'Jack',
        'last_name': 'Hudson',
    },
    {
        'first_name': 'Vanessa',
        'last_name': 'Watson',
    },
    {
        'first_name': 'Grace',
        'last_name': 'Dyer',
    },
    {
        'first_name': 'Natalie',
        'last_name': 'Wright',
    },
    {
        'first_name': 'Felicity',
        'last_name': 'Davies',
    },
    {
        'first_name': 'Yvonne',
        'last_name': 'Manning',
    },
    {
        'first_name': 'Phil',
        'last_name': 'North',
    },
    {
        'first_name': 'Lily',
        'last_name': 'Rutherford',
    },
    {
        'first_name': 'Chloe',
        'last_name': 'Hunter',
    },
    {
        'first_name': 'Bella',
        'last_name': 'Black',
    },
    {
        'first_name': 'Ruth',
        'last_name': 'Berry',
    },
    {
        'first_name': 'Stewart',
        'last_name': 'Lee',
    },
    {
        'first_name': 'Bella',
        'last_name': 'Peters',
    },
    {
        'first_name': 'Lisa',
        'last_name': 'Wallace',
    },
    {
        'first_name': 'Oliver',
        'last_name': 'Hudson',
    },
    {
        'first_name': 'Sarah',
        'last_name': 'Manning',
    },
    {
        'first_name': 'Richard',
        'last_name': 'Bond',
    },
    {
        'first_name': 'Cameron',
        'last_name': 'Metcalfe',
    },
    {
        'first_name': 'Penelope',
        'last_name': 'Clark',
    },
    {
        'first_name': 'Joshua',
        'last_name': 'Kerr',
    },
    {
        'first_name': 'Una',
        'last_name': 'Roberts',
    },
    {
        'first_name': 'Austin',
        'last_name': 'Newman',
    },
    {
        'first_name': 'Neil',
        'last_name': 'King',
    },
    {
        'first_name': 'Rachel',
        'last_name': 'Sutherland',
    },
    {
        'first_name': 'Dylan',
        'last_name': 'Nash',
    },
    {
        'first_name': 'Edward',
        'last_name': 'Davidson',
    },
    {
        'first_name': 'Claire',
        'last_name': 'Paige',
    },
    {
        'first_name': 'John',
        'last_name': 'Bell',
    },
    {
        'first_name': 'Wanda',
        'last_name': 'Ross',
    },
    {
        'first_name': 'Max',
        'last_name': 'Howard',
    },
    {
        'first_name': 'Tracey',
        'last_name': 'Walker',
    },
    {
        'first_name': 'Una',
        'last_name': 'Mackay',
    },
    {
        'first_name': 'Lillian',
        'last_name': 'MacLeod',
    },
    {
        'first_name': 'Lillian',
        'last_name': 'Black',
    },
    {
        'first_name': 'Wendy',
        'last_name': 'MacDonald',
    },
    {
        'first_name': 'Olivia',
        'last_name': 'Stewart',
    },
    {
        'first_name': 'Carol',
        'last_name': 'Gray',
    },
    {
        'first_name': 'Victoria',
        'last_name': 'Brown',
    },
    {
        'first_name': 'Victor',
        'last_name': 'Lee',
    },
    {
        'first_name': 'Kylie',
        'last_name': 'Clarkson',
    },
    {
        'first_name': 'Vanessa',
        'last_name': 'Dickens',
    },
    {
        'first_name': 'Boris',
        'last_name': 'Hill',
    },
    {
        'first_name': 'Steven',
        'last_name': 'Springer',
    },
    {
        'first_name': 'Olivia',
        'last_name': 'Dickens',
    },
    {
        'first_name': 'Jonathan',
        'last_name': 'Lewis',
    },
    {
        'first_name': 'Jane',
        'last_name': 'Lyman',
    },
    {
        'first_name': 'John',
        'last_name': 'Piper',
    },
    {
        'first_name': 'Colin',
        'last_name': 'Davidson',
    },
    {
        'first_name': 'Gordon',
        'last_name': 'Lawrence',
    },
    {
        'first_name': 'Neil',
        'last_name': 'Morrison',
    },
    {
        'first_name': 'Michael',
        'last_name': 'Peake',
    },
    {
        'first_name': 'Virginia',
        'last_name': 'Powell',
    },
    {
        'first_name': 'Julia',
        'last_name': 'Oliver',
    },
    {
        'first_name': 'Andrea',
        'last_name': 'Jackson',
    },
    {
        'first_name': 'Julia',
        'last_name': 'Ross',
    },
    {
        'first_name': 'Chloe',
        'last_name': 'Watson',
    },
    {
        'first_name': 'Emily',
        'last_name': 'Baker',
    },
    {
        'first_name': 'Colin',
        'last_name': 'Howard',
    },

]


def add_instructor_data(apps, schema_editor):
    instructor_class = apps.get_model('courseInfo', 'Instructor')
    for instructor in INSTRUCTORS:
        try:
            duplicate_object = instructor_class.objects.get(
                first_name=instructor['first_name'],
                last_name=instructor['last_name']
            )
            print('Duplicate instructor entry not added to instructor table:', instructor['first_name'], instructor['last_name'])
        except ObjectDoesNotExist:
            instructor_object = instructor_class.objects.create(
                first_name=instructor['first_name'],
                last_name=instructor['last_name']
            )


def remove_instructor_data(apps, schema_editor):
    instructor_class = apps.get_model('courseInfo', 'Instructor')
    for instructor in INSTRUCTORS:
        instructor_object = instructor_class.objects.get(
            first_name=instructor['first_name'],
            last_name=instructor['last_name']

        )
        instructor_object.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('courseInfo', '0009_auto_20191102_1539'),
    ]

    operations = [
        migrations.RunPython(
            add_instructor_data,
            remove_instructor_data
        )
    ]
